name = input()
cell = int(input())
wt = int(input())
money = int(input())
print("================Чек================")
print(f"Товар:{name:>29}")
print("Цена:{:>30}".format(f"{wt}кг * {cell}руб/кг"))
print("Итого:{:>29}".format(f"{cell*wt}руб"))
print("Внесено:{:>27}".format(f"{money}руб"))
print("Сдача:{:>29}".format(f"{money-cell*wt}руб"))
print("===================================")
